services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  freeswitch:
    image: safarov/freeswitch:latest
    container_name: freeswitch
    restart: unless-stopped
    network_mode: "host"   # FreeSWITCH often requires direct network access
    environment:
      - SOUND_RATES=8000:16000
      - SOUND_TYPES=music:en-us-callie
    ports:
      - "5066:5066"
      - "7443:7443"
      - "5060:5060"
    volumes:
      - ./freeswitch:/etc/freeswitch

volumes:
  pg_data:
  redis_data:
  freeswitch:
